import Footer from "@/components/Footer";
// import Header from "@/components/Header";
import type {Metadata} from "next";
import "./globals.css";

import NavBar from "@/components/Navbar";

export const metadata: Metadata = {
    title: "FERVENT",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className="overflow-x-hidden">
        {/* <NavBar />
        <main className="relative overflow-hidden">{children}</main>
        <Footer /> */}
        <main className=" w-full h-full mx-auto overflow-hidden ">
            <NavBar/>
            {children}
            <Footer/>
        </main>
        </body>
        </html>
    );
}
